var animap ={};
animap.list = [
{ effect: "bounce", name: "反弹" },
{ effect: "flash", name: "闪烁" },
{ effect: "pulse", name: "波动" },
{ effect: "rubberBand", name: "伸缩" },
{ effect: "shake", name: "摇动" },
{ effect: "swing", name: "摆动" },
{ effect: "tada", name: "抖动" },
{ effect: "wobble", name: "摇晃" },
{ effect: "bounceIn", name: "弹入" },
{ effect: "bounceInDown", name: "从上弹入" },
{ effect: "bounceInLeft", name: "从左弹入" },
{ effect: "bounceInRight", name: "从右弹入" },
{ effect: "bounceInUp", name: "从下弹出" },
{ effect: "bounceOut", name: "弹出" },
{ effect: "bounceOutDown", name: "向下弹出" },
{ effect: "bounceOutLeft", name: "向左弹出" },
{ effect: "bounceOutRight", name: "向右弹出" },
{ effect: "bounceOutUp", name: "向上弹出" },
{ effect: "fadeIn", name: "淡入" },
{ effect: "fadeInDown", name: "从上淡入" },
{ effect: "fadeInDownBig", name: "从上淡入(强)" },
{ effect: "fadeInLeft", name: "从左淡入" },
{ effect: "fadeInLeftBig", name: "从左淡入(强)" },
{ effect: "fadeInRight", name: "从右淡入" },
{ effect: "fadeInRightBig", name: "从右淡入(强)" },
{ effect: "fadeInUp", name: "从下淡入" },
{ effect: "fadeInUpBig", name: "从下淡入(强)" },
{ effect: "fadeOut", name: "淡出" },
{ effect: "fadeOutDown", name: "向下淡出" },
{ effect: "fadeOutDownBig", name: "向下淡出(强)" },
{ effect: "fadeOutLeft", name: "向左淡出" },
{ effect: "fadeOutLeftBig", name: "向左淡出(强)" },
{ effect: "fadeOutRight", name: "向右淡出" },
{ effect: "fadeOutRightBig", name: "向右淡出(强)" },
{ effect: "fadeOutUp", name: "向上淡出" },
{ effect: "fadeOutUpBig", name: "向上淡出(强)" },
{ effect: "flip", name: "翻转" },
{ effect: "flipInX", name: "垂直转入" },
{ effect: "flipInY", name: "水平转入" },
{ effect: "flipOutX", name: "垂直转出" },
{ effect: "flipOutY", name: "垂直转入" },
{ effect: "lightSpeedIn", name: "滑入" },
{ effect: "lightSpeedOut", name: "滑出" },
{ effect: "rotateIn", name: "旋进" },
{ effect: "rotateInDownLeft", name: "左上旋入" },
{ effect: "rotateInDownRight", name: "右上旋入" },
{ effect: "rotateInUpLeft", name: "左下旋入" },
{ effect: "rotateInUpRight", name: "右下旋入" },
{ effect: "rotateOut", name: "旋出" },
{ effect: "rotateOutDownLeft", name: "左下旋出" },
{ effect: "rotateOutDownRight", name: "右下旋出" },
{ effect: "rotateOutUpLeft", name: "左上旋出" },
{ effect: "rotateOutUpRight", name: "右上旋出" },
{ effect: "slideInUp", name: "从下滑入" },
{ effect: "slideInDown", name: "从上滑入" },
{ effect: "slideInLeft", name: "从左滑入" },
{ effect: "slideInRight", name: "从右滑入" },
{ effect: "slideOutUp", name: "向上滑出" },
{ effect: "slideOutDown", name: "向下滑出" },
{ effect: "slideOutLeft", name: "向左滑出" },
{ effect: "slideOutRight", name: "向右滑出" },
{ effect: "zoomIn", name: "放大" },
{ effect: "zoomInDown", name: "从上放大" },
{ effect: "zoomInLeft", name: "从左放大" },
{ effect: "zoomInRight", name: "从右放大" },
{ effect: "zoomInUp", name: "从下放大" },
{ effect: "zoomOut", name: "缩出" },
{ effect: "zoomOutDown", name: "向下缩出" },
{ effect: "zoomOutLeft", name: "向左缩出" },
{ effect: "zoomOutRight", name: "向右缩出" },
{ effect: "zoomOutUp", name: "向上缩出" },
{ effect: "hinge", name: "跌落" },
{ effect: "rollIn", name: "转入" },
{ effect: "rollOut", name: "转出" }
];
animap.getname = function (effect) {
    var def = "未设置";
    var ref = this;
    if (!effect || effect == "") { return def; }
    for (var i = 0; i < ref.list.length; i++) {
        var mod = ref.list[i];
        if (effect == mod.effect) { return mod.name; }
    }
    return def;
}