var MenuJson = [
    { "ID": "1", "Name": "我的工作台", "Visible": true, "css": "content shop page education office", "Child": [{ "ID": "1_1", "Name": "版本信息", "Visible": true, "css": "content shop page education office" }, { "ID": "1_2", "Name": "从此开始", "Visible": true, "css": "content shop page education office" }, { "ID": "1_3", "Name": "快速导航", "Visible": true, "css": "content shop page education office" }, { "ID": "1_4", "Name": "修改密码", "Visible": true, "css": "content shop page education office" }] },

    { "ID": "2", "Name": "内容管理", "Visible": true, "Child": [{ "ID": "2_1", "Name": "栏目管理", "Visible": true, "css": "content" }, { "ID": "2_2", "Name": "专题管理", "Visible": true, "css": "content" }, { "ID": "2_3", "Name": "评论管理", "Visible": true, "css": "content" }, { "ID": "2_4", "Name": "互动模块", "Visible": true, "css": "content" }, { "ID": "2_7", "Name": "生成发布", "Visible": true, "css": "content" }, { "ID": "2_6", "Name": "文件工厂", "Visible": true, "css": "content" }, { "ID": "2_5", "Name": "采集检索", "Visible": true, "css": "content" }, { "ID": "2_8", "Name": "回收站&nbsp&nbsp", "Visible": true, "css": "content" }, { "ID": "2_9", "Name": "问答贴吧", "Visible": true, "css": "content" }, { "ID": "2_10", "Name": "内容参数", "Visible": true, "css": "content" }, { "ID": "2_11", "Name": "访问评价", "Visible": true, "css": "content" }], "css": "content" },

    { "ID": "3", "Name": "商城管理", "Visible": true, "Child": [{ "ID": "3_1", "Name": "商品管理", "Visible": true, "css": "shop" }, { "ID": "3_2", "Name": "库存管理", "Visible": true, "css": "shop" }, { "ID": "3_3", "Name": "订单管理", "Visible": true, "css": "shop" }, { "ID": "3_4", "Name": "明细记录", "Visible": true, "css": "shop" }, { "ID": "3_5", "Name": "销售统计", "Visible": true, "css": "shop" }, { "ID": "3_6", "Name": "促销优惠", "Visible": true, "css": "shop" }, { "ID": "3_7", "Name": "商城配置", "Visible": true, "css": "shop" }, { "ID": "3_8", "Name": "加盟商&nbsp&nbsp", "Visible": true, "css": "shop" }, { "ID": "3_9", "Name": "商品回收", "Visible": true, "css": "shop" }, { "ID": "3_10", "Name": "礼品管理", "Visible": true, "css": "shop" },  { "ID": "3_12", "Name": "推广返利", "Visible": true, "css": "content shop" }, { "ID": "3_13", "Name": "店铺管理", "Visible": true, "css": "shop" }, { "ID": "3_14", "Name": "3D店铺", "Visible": true, "css": "shop" }], "css": "shop" },

    { "ID": "4", "Name": "企业黄页", "Visible": true, "Child": [{ "ID": "4_1", "Name": "黄页申请", "Visible": true, "css": "page" }, { "ID": "4_2", "Name": "黄页审核", "Visible": true, "css": "page" }, { "ID": "4_3", "Name": "栏目设定", "Visible": true, "css": "page" }, { "ID": "4_4", "Name": "内容管理", "Visible": true, "css": "page" }, { "ID": "4_5", "Name": "黄页模型", "Visible": true, "css": "page" }, { "ID": "4_6", "Name": "黄页样式", "Visible": true, "css": "page" }], "css": "page" },

    { "ID": "5", "Name": "教育模块", "Visible": true, "Child": [{ "ID": "5_1", "Name": "考试管理", "Visible": true, "css": "education" }, { "ID": "5_2", "Name": "阅卷中心", "Visible": true, "css": "education" }, { "ID": "5_3", "Name": "班级管理", "Visible": true, "css": "education" }, { "ID": "5_4", "Name": "学员管理", "Visible": true, "css": "education" }, { "ID": "5_5", "Name": "培训资源", "Visible": true, "css": "education" }, { "ID": "5_6", "Name": "财务管理", "Visible": true, "css": "education" }, { "ID": "5_7", "Name": "组卷管理", "Visible": true, "css": "education" }, { "ID": "5_8", "Name": "数字出版", "Visible": true, "css": "education" }], "css": "education" },

    { "ID": "6", "Name": "用户管理", "Visible": true, "Child": [{ "ID": "6_1", "Name": "会员管理", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_2", "Name": "管理员&nbsp&nbsp", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_3", "Name": "用户角色", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_4", "Name": "信息发送", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_5", "Name": "订阅中心", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_6", "Name": "人才招聘", "Visible": true, "css": "content shop page office config safe" }, { "ID": "6_7", "Name": "SNS社区", "Visible": true, "css": "content shop page office config safe" }], "css": "content shop page office config safe" },

    { "ID": "7", "Name": "扩展功能", "Visible": true, "Child": [{ "ID": "7_1", "Name": "开发中心", "Visible": true, "css": "shop page education config safe" }, { "ID": "7_2", "Name": "广告管理", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_3", "Name": "访问统计", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_4", "Name": "问卷调查", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_5", "Name": "文件管理", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_6", "Name": "数据字典", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_7", "Name": "站内链接", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_8", "Name": "客户端&nbsp&nbsp", "Visible": true, "css": "shop page education config safe" }, { "ID": "7_9", "Name": "移动微信", "Visible": true, "css": "content shop page education config safe" }, { "ID": "7_10", "Name": "其他功能", "Visible": true, "css": "shop page education config safe" }], "css": "content shop page education config safe" },

    { "ID": "8", "Name": "系统设置", "Visible": true, "css": "content shop page config safe" ,"Child": [{ "ID": "8_1", "Name": "网站配置", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_2", "Name": "模型管理", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_3", "Name": "节点管理", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_4", "Name": "流程管理", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_5", "Name": "专题管理", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_6", "Name": "模板风格", "Visible": true, "css": "content shop page config safe" }, { "ID": "8_7", "Name": "标签管理", "Visivle": true, "css": "content shop page config safe" }, { "ID": "8_8", "Name": "在线支付", "Visible": true, "css": "content shop page config safe" }]},

    { "ID": "9", "Name": "企业办公", "Visible": true, "css": "office", "Child": [{ "ID": "9_1", "Name": "OA配置", "Visible": true, "css": "shop page education office" }, { "ID": "9_9", "Name": "能力中心", "Visible": true, "css": "shop page education office" }, { "ID": "9_2", "Name": "组织结构", "Visible": true, "css": "shop page education office" }, { "ID": "9_3", "Name": "项目管理", "Visible": true, "css": "shop page education office" }, { "ID": "9_4", "Name": "CRM管理", "Visible": true, "css": "shop page education office" }, { "ID": "9_5", "Name": "有问必答", "Visible": true, "css": "shop page education office" }, { "ID": "9_6", "Name": "客服通&nbsp&nbsp", "Visible": true, "css": "shop page education office" }, { "ID": "9_7", "Name": "工作统计", "Visible": true, "css": "shop page education office" }, { "ID": "9_8", "Name": "日志管理", "Visible": true, "css": "shop page education office" }], "css": "shop page education office config" },
    { "ID": "10", "Name": "移动", "Visible": true,   "css": "content", "Child": [{ "ID": "10_1", "Name": "移动应用", "Visible": true, "css": "mobile" }, { "ID": "10_2", "Name": "微信应用", "Visible": true, "css": "mobile" }, { "ID": "10_3", "Name": "微信支付", "Visible": true, "css": "mobile" }, { "ID": "10_4", "Name": "微信配置", "Visible": true, "css": "mobile" }, { "ID": "10_5", "Name": "菜单配置", "Visible": true, "css": "mobile" }, { "ID": "10_6", "Name": "移动浏览", "Visible": true, "css": "mobile" }] },
    { "ID": "11", "Name": "站群", "Visible": true,   "css": "content","Child": [{ "ID": "11_1", "Name": "全局配置", "Visible": true, "css": "site" }, { "ID": "11_2", "Name": "服务器集", "Visible": true, "css": "site" }, { "ID": "11_3", "Name": "数据管理", "Visible": true, "css": "site" }, { "ID": "11_4", "Name": "站点列表", "Visible": true, "css": "site" }, { "ID": "11_5", "Name": "应用程序", "Visible": true, "css": "site" }, { "ID": "11_6", "Name": "模板云台", "Visible": true, "css": "site" }, { "ID": "11_7", "Name": "快云安装", "Visible": true, "css": "site" }, { "ID": "11_8", "Name": "智能采集", "Visible": true, "css": "site" }, { "ID": "11_9", "Name": "域名注册", "Visible": true, "css": "site" }] }];
