//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ZoomLa.AppCode.cn.woxp.gateway {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSMSSoap", Namespace="http://woxp.cn/")]
    public partial class WebSMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetErrorHintOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditPWDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentityMarkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoneyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBalanceCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback MMS_GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBadKeyWordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendXMLPackOperationCompleted;
        
        private System.Threading.SendOrPostCallback FastSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback FastSendLongSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpSMSTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadXmlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebSMS() {
            this.Url = global::ZoomLa.AppCode.Properties.Settings.Default.ZoomLa_AppCode_cn_woxp_gateway_WebSMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetErrorHintCompletedEventHandler GetErrorHintCompleted;
        
        /// <remarks/>
        public event EditPWDCompletedEventHandler EditPWDCompleted;
        
        /// <remarks/>
        public event GetIdentityMarkCompletedEventHandler GetIdentityMarkCompleted;
        
        /// <remarks/>
        public event GetMoneyCompletedEventHandler GetMoneyCompleted;
        
        /// <remarks/>
        public event GetBalanceCountCompletedEventHandler GetBalanceCountCompleted;
        
        /// <remarks/>
        public event MMS_GetBalanceCompletedEventHandler MMS_GetBalanceCompleted;
        
        /// <remarks/>
        public event GetBadKeyWordsCompletedEventHandler GetBadKeyWordsCompleted;
        
        /// <remarks/>
        public event SendXMLPackCompletedEventHandler SendXMLPackCompleted;
        
        /// <remarks/>
        public event FastSendCompletedEventHandler FastSendCompleted;
        
        /// <remarks/>
        public event FastSendLongSMSCompletedEventHandler FastSendLongSMSCompleted;
        
        /// <remarks/>
        public event GetUpSMSCompletedEventHandler GetUpSMSCompleted;
        
        /// <remarks/>
        public event GetUpSMSTableCompletedEventHandler GetUpSMSTableCompleted;
        
        /// <remarks/>
        public event ReadXmlCompletedEventHandler ReadXmlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetErrorHint", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetErrorHint(int ErrorId) {
            object[] results = this.Invoke("GetErrorHint", new object[] {
                        ErrorId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorHintAsync(int ErrorId) {
            this.GetErrorHintAsync(ErrorId, null);
        }
        
        /// <remarks/>
        public void GetErrorHintAsync(int ErrorId, object userState) {
            if ((this.GetErrorHintOperationCompleted == null)) {
                this.GetErrorHintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorHintOperationCompleted);
            }
            this.InvokeAsync("GetErrorHint", new object[] {
                        ErrorId}, this.GetErrorHintOperationCompleted, userState);
        }
        
        private void OnGetErrorHintOperationCompleted(object arg) {
            if ((this.GetErrorHintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorHintCompleted(this, new GetErrorHintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/EditPWD", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EditPWD(string eid_pwd_md5, string newPwd) {
            object[] results = this.Invoke("EditPWD", new object[] {
                        eid_pwd_md5,
                        newPwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EditPWDAsync(string eid_pwd_md5, string newPwd) {
            this.EditPWDAsync(eid_pwd_md5, newPwd, null);
        }
        
        /// <remarks/>
        public void EditPWDAsync(string eid_pwd_md5, string newPwd, object userState) {
            if ((this.EditPWDOperationCompleted == null)) {
                this.EditPWDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditPWDOperationCompleted);
            }
            this.InvokeAsync("EditPWD", new object[] {
                        eid_pwd_md5,
                        newPwd}, this.EditPWDOperationCompleted, userState);
        }
        
        private void OnEditPWDOperationCompleted(object arg) {
            if ((this.EditPWDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditPWDCompleted(this, new EditPWDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetIdentityMark", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetIdentityMark(int Eid, string uid, string pwd, int gateId) {
            object[] results = this.Invoke("GetIdentityMark", new object[] {
                        Eid,
                        uid,
                        pwd,
                        gateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentityMarkAsync(int Eid, string uid, string pwd, int gateId) {
            this.GetIdentityMarkAsync(Eid, uid, pwd, gateId, null);
        }
        
        /// <remarks/>
        public void GetIdentityMarkAsync(int Eid, string uid, string pwd, int gateId, object userState) {
            if ((this.GetIdentityMarkOperationCompleted == null)) {
                this.GetIdentityMarkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentityMarkOperationCompleted);
            }
            this.InvokeAsync("GetIdentityMark", new object[] {
                        Eid,
                        uid,
                        pwd,
                        gateId}, this.GetIdentityMarkOperationCompleted, userState);
        }
        
        private void OnGetIdentityMarkOperationCompleted(object arg) {
            if ((this.GetIdentityMarkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentityMarkCompleted(this, new GetIdentityMarkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetMoney", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetMoney(string eid_pwd_md5) {
            object[] results = this.Invoke("GetMoney", new object[] {
                        eid_pwd_md5});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoneyAsync(string eid_pwd_md5) {
            this.GetMoneyAsync(eid_pwd_md5, null);
        }
        
        /// <remarks/>
        public void GetMoneyAsync(string eid_pwd_md5, object userState) {
            if ((this.GetMoneyOperationCompleted == null)) {
                this.GetMoneyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoneyOperationCompleted);
            }
            this.InvokeAsync("GetMoney", new object[] {
                        eid_pwd_md5}, this.GetMoneyOperationCompleted, userState);
        }
        
        private void OnGetMoneyOperationCompleted(object arg) {
            if ((this.GetMoneyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoneyCompleted(this, new GetMoneyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetBalanceCount", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetBalanceCount(string eid_pwd_md5) {
            object[] results = this.Invoke("GetBalanceCount", new object[] {
                        eid_pwd_md5});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceCountAsync(string eid_pwd_md5) {
            this.GetBalanceCountAsync(eid_pwd_md5, null);
        }
        
        /// <remarks/>
        public void GetBalanceCountAsync(string eid_pwd_md5, object userState) {
            if ((this.GetBalanceCountOperationCompleted == null)) {
                this.GetBalanceCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceCountOperationCompleted);
            }
            this.InvokeAsync("GetBalanceCount", new object[] {
                        eid_pwd_md5}, this.GetBalanceCountOperationCompleted, userState);
        }
        
        private void OnGetBalanceCountOperationCompleted(object arg) {
            if ((this.GetBalanceCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceCountCompleted(this, new GetBalanceCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/MMS_GetBalance", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MMS_GetBalance(string eid_pwd_md5) {
            object[] results = this.Invoke("MMS_GetBalance", new object[] {
                        eid_pwd_md5});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MMS_GetBalanceAsync(string eid_pwd_md5) {
            this.MMS_GetBalanceAsync(eid_pwd_md5, null);
        }
        
        /// <remarks/>
        public void MMS_GetBalanceAsync(string eid_pwd_md5, object userState) {
            if ((this.MMS_GetBalanceOperationCompleted == null)) {
                this.MMS_GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMMS_GetBalanceOperationCompleted);
            }
            this.InvokeAsync("MMS_GetBalance", new object[] {
                        eid_pwd_md5}, this.MMS_GetBalanceOperationCompleted, userState);
        }
        
        private void OnMMS_GetBalanceOperationCompleted(object arg) {
            if ((this.MMS_GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MMS_GetBalanceCompleted(this, new MMS_GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetBadKeyWords", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBadKeyWords(string eid_pwd_gateId) {
            object[] results = this.Invoke("GetBadKeyWords", new object[] {
                        eid_pwd_gateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBadKeyWordsAsync(string eid_pwd_gateId) {
            this.GetBadKeyWordsAsync(eid_pwd_gateId, null);
        }
        
        /// <remarks/>
        public void GetBadKeyWordsAsync(string eid_pwd_gateId, object userState) {
            if ((this.GetBadKeyWordsOperationCompleted == null)) {
                this.GetBadKeyWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBadKeyWordsOperationCompleted);
            }
            this.InvokeAsync("GetBadKeyWords", new object[] {
                        eid_pwd_gateId}, this.GetBadKeyWordsOperationCompleted, userState);
        }
        
        private void OnGetBadKeyWordsOperationCompleted(object arg) {
            if ((this.GetBadKeyWordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBadKeyWordsCompleted(this, new GetBadKeyWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/SendXMLPack", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult SendXMLPack(string eid_pwd_gateId, string xml) {
            object[] results = this.Invoke("SendXMLPack", new object[] {
                        eid_pwd_gateId,
                        xml});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendXMLPackAsync(string eid_pwd_gateId, string xml) {
            this.SendXMLPackAsync(eid_pwd_gateId, xml, null);
        }
        
        /// <remarks/>
        public void SendXMLPackAsync(string eid_pwd_gateId, string xml, object userState) {
            if ((this.SendXMLPackOperationCompleted == null)) {
                this.SendXMLPackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendXMLPackOperationCompleted);
            }
            this.InvokeAsync("SendXMLPack", new object[] {
                        eid_pwd_gateId,
                        xml}, this.SendXMLPackOperationCompleted, userState);
        }
        
        private void OnSendXMLPackOperationCompleted(object arg) {
            if ((this.SendXMLPackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendXMLPackCompleted(this, new SendXMLPackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/FastSend", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult FastSend(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId) {
            object[] results = this.Invoke("FastSend", new object[] {
                        eid_pwd_gateId,
                        TargetNo,
                        MsgContent,
                        SendTime,
                        strSubId});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void FastSendAsync(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId) {
            this.FastSendAsync(eid_pwd_gateId, TargetNo, MsgContent, SendTime, strSubId, null);
        }
        
        /// <remarks/>
        public void FastSendAsync(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId, object userState) {
            if ((this.FastSendOperationCompleted == null)) {
                this.FastSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFastSendOperationCompleted);
            }
            this.InvokeAsync("FastSend", new object[] {
                        eid_pwd_gateId,
                        TargetNo,
                        MsgContent,
                        SendTime,
                        strSubId}, this.FastSendOperationCompleted, userState);
        }
        
        private void OnFastSendOperationCompleted(object arg) {
            if ((this.FastSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FastSendCompleted(this, new FastSendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/FastSendLongSMS", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult FastSendLongSMS(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId) {
            object[] results = this.Invoke("FastSendLongSMS", new object[] {
                        eid_pwd_gateId,
                        TargetNo,
                        MsgContent,
                        SendTime,
                        strSubId});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public void FastSendLongSMSAsync(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId) {
            this.FastSendLongSMSAsync(eid_pwd_gateId, TargetNo, MsgContent, SendTime, strSubId, null);
        }
        
        /// <remarks/>
        public void FastSendLongSMSAsync(string eid_pwd_gateId, string TargetNo, string MsgContent, string SendTime, string strSubId, object userState) {
            if ((this.FastSendLongSMSOperationCompleted == null)) {
                this.FastSendLongSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFastSendLongSMSOperationCompleted);
            }
            this.InvokeAsync("FastSendLongSMS", new object[] {
                        eid_pwd_gateId,
                        TargetNo,
                        MsgContent,
                        SendTime,
                        strSubId}, this.FastSendLongSMSOperationCompleted, userState);
        }
        
        private void OnFastSendLongSMSOperationCompleted(object arg) {
            if ((this.FastSendLongSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FastSendLongSMSCompleted(this, new FastSendLongSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetUpSMS", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Woxp_UpSMS[] GetUpSMS(string eid_pwd_gateId) {
            object[] results = this.Invoke("GetUpSMS", new object[] {
                        eid_pwd_gateId});
            return ((Woxp_UpSMS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUpSMSAsync(string eid_pwd_gateId) {
            this.GetUpSMSAsync(eid_pwd_gateId, null);
        }
        
        /// <remarks/>
        public void GetUpSMSAsync(string eid_pwd_gateId, object userState) {
            if ((this.GetUpSMSOperationCompleted == null)) {
                this.GetUpSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpSMSOperationCompleted);
            }
            this.InvokeAsync("GetUpSMS", new object[] {
                        eid_pwd_gateId}, this.GetUpSMSOperationCompleted, userState);
        }
        
        private void OnGetUpSMSOperationCompleted(object arg) {
            if ((this.GetUpSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpSMSCompleted(this, new GetUpSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/GetUpSMSTable", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUpSMSTable(string eid_pwd_gateId) {
            object[] results = this.Invoke("GetUpSMSTable", new object[] {
                        eid_pwd_gateId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpSMSTableAsync(string eid_pwd_gateId) {
            this.GetUpSMSTableAsync(eid_pwd_gateId, null);
        }
        
        /// <remarks/>
        public void GetUpSMSTableAsync(string eid_pwd_gateId, object userState) {
            if ((this.GetUpSMSTableOperationCompleted == null)) {
                this.GetUpSMSTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpSMSTableOperationCompleted);
            }
            this.InvokeAsync("GetUpSMSTable", new object[] {
                        eid_pwd_gateId}, this.GetUpSMSTableOperationCompleted, userState);
        }
        
        private void OnGetUpSMSTableOperationCompleted(object arg) {
            if ((this.GetUpSMSTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpSMSTableCompleted(this, new GetUpSMSTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://woxp.cn/ReadXml", RequestNamespace="http://woxp.cn/", ResponseNamespace="http://woxp.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadXml(string eid_pwd_gateId) {
            object[] results = this.Invoke("ReadXml", new object[] {
                        eid_pwd_gateId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadXmlAsync(string eid_pwd_gateId) {
            this.ReadXmlAsync(eid_pwd_gateId, null);
        }
        
        /// <remarks/>
        public void ReadXmlAsync(string eid_pwd_gateId, object userState) {
            if ((this.ReadXmlOperationCompleted == null)) {
                this.ReadXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadXmlOperationCompleted);
            }
            this.InvokeAsync("ReadXml", new object[] {
                        eid_pwd_gateId}, this.ReadXmlOperationCompleted, userState);
        }
        
        private void OnReadXmlOperationCompleted(object arg) {
            if ((this.ReadXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadXmlCompleted(this, new ReadXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woxp.cn/")]
    public partial class SendResult {
        
        private string statusReportIdField;
        
        private int retCodeField;
        
        private string gateWayRetutrnField;
        
        private int gateWayIdField;
        
        private string gateWayRetutrn_CnField;
        
        private string blackWordsField;
        
        private string failNoField;
        
        private string shieldNoField;
        
        private string errorDescField;
        
        private int nSSRIDField;
        
        /// <remarks/>
        public string StatusReportId {
            get {
                return this.statusReportIdField;
            }
            set {
                this.statusReportIdField = value;
            }
        }
        
        /// <remarks/>
        public int RetCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GateWayRetutrn {
            get {
                return this.gateWayRetutrnField;
            }
            set {
                this.gateWayRetutrnField = value;
            }
        }
        
        /// <remarks/>
        public int GateWayId {
            get {
                return this.gateWayIdField;
            }
            set {
                this.gateWayIdField = value;
            }
        }
        
        /// <remarks/>
        public string GateWayRetutrn_Cn {
            get {
                return this.gateWayRetutrn_CnField;
            }
            set {
                this.gateWayRetutrn_CnField = value;
            }
        }
        
        /// <remarks/>
        public string BlackWords {
            get {
                return this.blackWordsField;
            }
            set {
                this.blackWordsField = value;
            }
        }
        
        /// <remarks/>
        public string FailNo {
            get {
                return this.failNoField;
            }
            set {
                this.failNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShieldNo {
            get {
                return this.shieldNoField;
            }
            set {
                this.shieldNoField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public int nSSRID {
            get {
                return this.nSSRIDField;
            }
            set {
                this.nSSRIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://woxp.cn/")]
    public partial class Woxp_UpSMS {
        
        private int nSidField;
        
        private string strMobileField;
        
        private string msgField;
        
        private string repTimeField;
        
        private string subNoField;
        
        private string sP_IDField;
        
        /// <remarks/>
        public int nSid {
            get {
                return this.nSidField;
            }
            set {
                this.nSidField = value;
            }
        }
        
        /// <remarks/>
        public string strMobile {
            get {
                return this.strMobileField;
            }
            set {
                this.strMobileField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string RepTime {
            get {
                return this.repTimeField;
            }
            set {
                this.repTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SubNo {
            get {
                return this.subNoField;
            }
            set {
                this.subNoField = value;
            }
        }
        
        /// <remarks/>
        public string SP_ID {
            get {
                return this.sP_IDField;
            }
            set {
                this.sP_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetErrorHintCompletedEventHandler(object sender, GetErrorHintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorHintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorHintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void EditPWDCompletedEventHandler(object sender, EditPWDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditPWDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditPWDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetIdentityMarkCompletedEventHandler(object sender, GetIdentityMarkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentityMarkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentityMarkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMoneyCompletedEventHandler(object sender, GetMoneyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoneyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoneyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetBalanceCountCompletedEventHandler(object sender, GetBalanceCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MMS_GetBalanceCompletedEventHandler(object sender, MMS_GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MMS_GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MMS_GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetBadKeyWordsCompletedEventHandler(object sender, GetBadKeyWordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBadKeyWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBadKeyWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendXMLPackCompletedEventHandler(object sender, SendXMLPackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendXMLPackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendXMLPackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FastSendCompletedEventHandler(object sender, FastSendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FastSendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FastSendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FastSendLongSMSCompletedEventHandler(object sender, FastSendLongSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FastSendLongSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FastSendLongSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUpSMSCompletedEventHandler(object sender, GetUpSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Woxp_UpSMS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Woxp_UpSMS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUpSMSTableCompletedEventHandler(object sender, GetUpSMSTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpSMSTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpSMSTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadXmlCompletedEventHandler(object sender, ReadXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591